### ISSUE TITLE
Build command not exists 

### ISSUE THREAD

**Issue by marcinsydor** [dart-bridge/bridge#2]
Hi Emil, I've updated bridge to 1.0.0-alpha1+6 and build command gone. How I can compile front end scripts?

Cheers
Marcin

**Comment by emilniklas** [comment]
The command is coming back soon. For now, use `dart2js -m -o web/main.dart.js web/main.dart`

**Comment by marcinsydor** [comment]
I can compile it now but main.dart.js is not embedded to html file. I'm guessing it's what build command does. I will get back to previous version and use new version when the command will get back.  Thanks for quick reply.

**Comment by emilniklas** [comment]
Alpha 1+7 comes out today. This is all fixed then

**Comment by emilniklas** [comment]
This is now resolved! :)

**Comment by emilniklas** [comment]
In `1.0.0alpha1+7` that is

**Comment by marcinsydor** [comment]
Thanks Emil, I've updated the framework and boilerplate to the latest versions. When I use build I'm getting error:

```
The null object does not have a method 'list'.

    NoSuchMethodError: method not found: 'list'
    Receiver: null
    Arguments: [followLinks: false, recursive: true]

```

**Comment by emilniklas** [comment]
Have you got any .dart files in your web directory?

**Comment by emilniklas** [comment]
Thank you, this was totally my fault. Try a quick update to `1.0.0-alpha1+8` and this issue will be fixed

**Comment by marcinsydor** [comment]
Thanks, the build is working now. I have the latest boilerplate. 
I see the templates are also changed.  The main.dart.js is not included in generated html. So I've added it myself:
`<script src="main.dart.js" type="text/javascript" />`.
I've added print line to the top of main function but see nothing in the browser dev tool.

**Comment by emilniklas** [comment]
This too is undocumented, I'm working on that right now:

In your root folder there is a file called `.env` in which you will see the following text:

```
APP_ENV=development
```

This file is where we set environment specific settings. If you either rename the file to something else than `.env` OR change the value of `APP_ENV` to `production` the script tag included in the template will be the javascript. As long as that file is present, and `APP_ENV` is not set to `production`, the script tag will reference main.dart.

During development, it's recommended to use Chromium (Dartium)

**Comment by emilniklas** [comment]
Example:

``` dart
// Controller
class SomeController {
  index() {
    return template('index', withScript: 'main');
  }
}
```

``` html
<!-- lib/templates/index.html -->
<html>
<head>
</head>
<body>
Hello
</body>
</html>
```

_.env_

```
APP_ENV=production
```

Given these files, the following document should be sent to the browser:

``` html
<!-- lib/templates/index.html -->
<html>
<head>
</head>
<body>
Hello
<script src='main.dart.js'></script></body>
</html>
```

If `.env` instead contains `APP_ENV=development` the output should be:

``` html
<!-- lib/templates/index.html -->
<html>
<head>
</head>
<body>
Hello
<script type='application/dart' src='main.dart'></script></body>
</html>
```
