### ISSUE TITLE
Shelf Routing

### ISSUE THREAD

**Issue by korsvanloon** [dart-bridge/bridge#7]
Hey,

First of all: very nice framework. I really like your templating system which feels very natural for Dart :)

However, I've got a little problem. I'm trying to connect Bridge with [shelf auth](https://pub.dartlang.org/packages/shelf_auth) but it's really hard with your custom Routing architecture.

I want to add the auth middleware to specific ranges of routes. But your custom Routing first of all can't do that and second of all I can't filter this shelf auth middleware. For example, I can't do this:

``` dart
router.get('/', controller.index, ignoreMiddleware: [AuthenticationMiddleware]);
```

because the type of the Middleware is actually a function resulting in `(Handler) => Handler`. The shelf AuthenticationMiddleware is  a real (class) type. Very confusing terminology btw :(

Obviously I also can't just ignore middleware by setting it to false because the index needs other middleware like tether.

With normal shelf routing I can easily configure a route hierarchy with middleware like this:

``` dart
rootRouter.child('/authenticated', middleware: defaultAuthMiddleware)
    ..get('/foo', (Request request) => new Response.ok(
        "Doing foo as ${loggedInUsername(request)}\n"));
```

Your framework would be perfect with shelf routing integrated!

**Comment by emilniklas** [comment]
Hello!

Thanks for your kind words :) I've been thinking to replace the router with a community maintained one. However there must be at least one level of abstraction to provide the response handler with dependency injection.

I'll see what I can do! In the meantime, you should be able to add shelf routing as a regular middleware, and use it instead of the built in router.

**Comment by korsvanloon** [comment]
Thank you very much for your quick response!

I'll try that :)

**Comment by korsvanloon** [comment]
You might want to take a look at this: [shelf_rest](https://pub.dartlang.org/packages/shelf_rest)

**Comment by emilniklas** [comment]
The router has been improved in the dev branch. The change is breaking, though. Closing this issue, but if you have further feature requests now or after the new router is released, please create separate issues on https://github.com/dart-bridge/framework
